services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: contractflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - contractflow_sql_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    image: contractflow-api:latest
    container_name: contractflow-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ContractFlowDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ContractFlow
      Jwt__Audience: ContractFlow
    ports:
      - "5149:8080"
    restart: unless-stopped

  frontend:
    image: contractflow-web:latest
    container_name: contractflow-web
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  contractflow_sql_data: